alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: shiny-app-gh
region: nyc
services:
- http_port: 8080
  image:
    registry: analythium
    registry_type: DOCKER_HUB
    repository: gh-action-test
    tag: latest
  instance_count: 1
  instance_size_slug: basic-xxs
  name: shiny-app
  routes:
  - path: /
  run_command: R -e "shiny::runApp('/home/app', host = '0.0.0.0', port=as.numeric(Sys.getenv('PORT')))"
  source_dir: /