name: shiny-app-test
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
region: nyc
services:
- name: ${IMAGE_NAME}
  http_port: 8080
  image:
    registry: ${REGISTRY}
    registry_type: DOCKER_HUB
    repository: ${IMAGE_NAME}
    tag: ${GITHUB_SHA}
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  run_command: R -e "shiny::runApp('/home/app', host = '0.0.0.0', port=as.numeric(Sys.getenv('PORT')))"
  source_dir: /
