name: Build Shiny Docker Image and Deploy to DO App Platform

on:
  push:
    branches:
      - main

jobs:
  app1:
    name: Build and deploy Shiny app
    runs-on: ubuntu-latest
    ## edit env vars here
    env:
      REGISTRY: "analythium"
      IMAGE_NAME: "github-action-test"
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      ## add your test steps here

      - name: Docker build and push with cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          image_name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          image_tag: ${{ github.sha }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Update app spec and publish app in App Platform
        env:
          APP_ID: ${{ secrets.APP_ID }}
        run: |
          envsubst < app.yaml > update.yaml
          doctl apps update ${APP_ID} --spec update.yaml
