name: Build Shiny Docker Image and Deploy to DO App Platform

on:
  push:
    branches:
      - main

jobs:
  app1:
    name: Build and deploy Shiny app
    runs-on: ubuntu-latest
    env:
      REGISTRY: "analythium"
      REPOSITORY: "gh-action-test"
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      ## add here your test steps here

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Docker build with cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          image_name: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
          image_tag: ${{ github.sha }}

      - name: Update app spec
        run: |
          cat > update.yaml << EOF
          alerts:
          - rule: DEPLOYMENT_FAILED
          - rule: DOMAIN_FAILED
          name: shiny-app-gh
          region: nyc
          services:
          - http_port: 8080
            image:
              registry: ${REGISTRY}
              registry_type: DOCKER_HUB
              repository: ${REPOSITORY}
              tag: ${GITHUB_SHA}
            instance_count: 1
            instance_size_slug: basic-xxs
            name: shiny-app
            routes:
            - path: /
            run_command: R -e "shiny::runApp('/home/app', host = '0.0.0.0', port=as.numeric(Sys.getenv('PORT')))"
            source_dir: /
          EOF

      - name: Update app in App Platform
        env:
          APP_ID: ${{ secrets.APP_ID }}
        run: |
          doctl apps update ${APP_ID} --spec update.yaml
